name: soft_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - freetype=2.12.1
  - jpeg=9e
  - lcms2=2.14
  - lerc=4.0.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.2
  - libpng=1.6.39
  - libsqlite=3.40.0
  - libtiff=4.5.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.13
  - ncurses=6.3
  - openjpeg=2.5.0
  - openssl=3.0.8
  - pillow=9.4.0
  - pip=23.0.1
  - pthread-stubs=0.4
  - python=3.8.16
  - python_abi=3.8
  - readline=8.1.2
  - setuptools=67.4.0
  - tk=8.6.12
  - wheel=0.38.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zstd=1.5.2
  - pip:
      - customtkinter==5.1.2
      - darkdetect==0.8.0
